### PR TITLE
week5 作業

### PR DESCRIPTION
**Pull request by JieRuLee**
老師好
week5 作業再麻煩您

姓名：李杰儒
Discord ：Jeff Lee

網址：
http://35.73.62.186:3000/

### CODE REVIEW

**Comment by JieRuLee** [comment]
老師好
week5 作業再麻煩您

姓名：李杰儒
Discord ：Jeff Lee

網址：
http://35.73.62.186:3000/

**Comment by cwpeng** [comment]
I think you made some good details in your webpages.

But, in booking.html, we should use name of signed in user for welcome message, not Yakko.

**Comment by JieRuLee** [comment]
老師好
week5 作業再麻煩您

姓名：李杰儒
Discord ：Jeff Lee

網址：
http://35.73.62.186:3000/

**Review by cwpeng — APPROVED** [review]
OK. Well Done.

**Pull request merged**
