### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by JieRuLee**
老師好
week1 作業再麻煩您過目

姓名：李杰儒
Discord ：Jeff Lee

網址：
http://52.197.14.170:3000/api/attractions?page=1
[http://52.197.14.170:3000/api/attractions?page=0&keyword=藝術](http://52.197.14.170:3000/api/attractions?page=0&keyword=%E8%97%9D%E8%A1%93)
http://52.197.14.170:3000/api/attraction/20

### CODE REVIEW

**Comment by JieRuLee** [comment]
老師好
week1 作業再麻煩您過目

姓名：李杰儒
Discord ：Jeff Lee

網址：
http://52.197.14.170:3000/api/attractions?page=1
http://52.197.14.170:3000/api/attractions?page=0&keyword=藝術
http://52.197.14.170:3000/api/attraction/20

**Comment by cwpeng** [comment]
1. "images" field should be an array containing image URLs separately, not a string.
2. "nextPage" should be current page plus 1, for example, "nextPage" of http://52.197.14.170:3000/api/attractions?page=0 should be 1.
3. keyword search results only contains 12 attractions per page, but yours will show all result data, for example, http://52.197.14.170:3000/api/attractions?page=0&keyword=%E5%8C%97 should only contain 12 attractions.

Fix issues and leave comment for me to review again.

**Comment by JieRuLee** [comment]
老師好
作業已修改，再麻煩您，謝謝。

姓名：李杰儒
Discord ：Jeff Lee

網址：
http://52.197.14.170:3000/api/attractions?page=1
http://52.197.14.170:3000/api/attractions?page=0&keyword=藝術
http://52.197.14.170:3000/api/attraction/20

**Comment by cwpeng** [comment]
1. OK.
2. OK.
3. No fix.

**Comment by JieRuLee** [comment]
老師好
第三點已修改完成，再麻煩您，謝謝。

姓名：李杰儒
Discord ：Jeff Lee

網址：
http://52.197.14.170:3000/api/attractions?page=1
http://52.197.14.170:3000/api/attractions?page=0&keyword=藝術
http://52.197.14.170:3000/api/attraction/20

**Comment by cwpeng** [comment]
OK. But two more issues:
1. "nextPage" of http://52.197.14.170:3000/api/attractions?page=0&keyword=%E5%8C%97 should be 1, not null. Because there are total 2 pages of search results of 北.
2. response format of http://52.197.14.170:3000/api/attraction/20 is incorrect. try to check API spec carefully.

**Comment by JieRuLee** [comment]
老師好
問題已修改完成，再麻煩您，謝謝。

姓名：李杰儒
Discord ：Jeff Lee

網址：
http://52.197.14.170:3000/api/attractions?page=1
http://52.197.14.170:3000/api/attractions?page=0&keyword=北
http://52.197.14.170:3000/api/attraction/20

**Comment by cwpeng** [comment]
1. OK.
2. No fix. and there should be more than 1 images in many attractions.

**Comment by JieRuLee** [comment]
老師好
狀態碼與API格式已修改完成，再麻煩您，謝謝。

姓名：李杰儒
Discord ：Jeff Lee

網址：
http://52.197.14.170:3000/api/attractions?page=1
http://52.197.14.170:3000/api/attractions?page=0&keyword=北
http://52.197.14.170:3000/api/attraction/20

**Comment by cwpeng** [comment]
Your server is broken now, cannot test it.

**Comment by JieRuLee** [comment]
老師好
網站已修改完成，再麻煩您，謝謝。

姓名：李杰儒
Discord ：Jeff Lee

http://35.73.62.186:3000/api/attractions?page=1
http://35.73.62.186:3000/api/attractions?page=0&keyword=北
http://35.73.62.186:3000/api/attraction/20

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going.

**Comment by JieRuLee** [comment]
老師好
week2 作業再麻煩您過目

姓名：李杰儒
Discord ：Jeff Lee

網址：
http://35.73.62.186:3000/

**Comment by cwpeng** [comment]
If you want me to review another weekly task, open a pull request for that.

**Pull request merged**
